(function(C){"object"===typeof exports&&"undefined"!==typeof module?module.exports=C():"function"===typeof define&&define.amd?define([],C):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).Slidy=C()})(function(){return function a(d,g,b){function c(h,k){if(!g[h]){if(!d[h]){var l="function"==typeof require&&require;if(!k&&l)return l(h,!0);if(e)return e(h,!0);l=Error("Cannot find module '"+h+"'");throw l.code="MODULE_NOT_FOUND",l;}l=g[h]={exports:{}};
d[h][0].call(l.exports,function(a){var b=d[h][1][a];return c(b?b:a)},l,l.exports,a,d,g,b)}return g[h].exports}for(var e="function"==typeof require&&require,h=0;h<b.length;h++)c(b[h]);return c}({1:[function(a,d,g){function b(){this._events=this._events||{};this._maxListeners=this._maxListeners||void 0}function c(a){return"function"===typeof a}function e(a){return"object"===typeof a&&null!==a}d.exports=b;b.EventEmitter=b;b.prototype._events=void 0;b.prototype._maxListeners=void 0;b.defaultMaxListeners=
10;b.prototype.setMaxListeners=function(a){if("number"!==typeof a||0>a||isNaN(a))throw TypeError("n must be a positive number");this._maxListeners=a;return this};b.prototype.emit=function(a){var f,b,l,d;this._events||(this._events={});if("error"===a&&(!this._events.error||e(this._events.error)&&!this._events.error.length)){f=arguments[1];if(f instanceof Error)throw f;throw TypeError('Uncaught, unspecified "error" event.');}b=this._events[a];if(void 0===b)return!1;if(c(b))switch(arguments.length){case 1:b.call(this);
break;case 2:b.call(this,arguments[1]);break;case 3:b.call(this,arguments[1],arguments[2]);break;default:f=arguments.length;l=Array(f-1);for(d=1;d<f;d++)l[d-1]=arguments[d];b.apply(this,l)}else if(e(b)){f=arguments.length;l=Array(f-1);for(d=1;d<f;d++)l[d-1]=arguments[d];b=b.slice();f=b.length;for(d=0;d<f;d++)b[d].apply(this,l)}return!0};b.prototype.addListener=function(a,f){var k;if(!c(f))throw TypeError("listener must be a function");this._events||(this._events={});this._events.newListener&&this.emit("newListener",
a,c(f.listener)?f.listener:f);this._events[a]?e(this._events[a])?this._events[a].push(f):this._events[a]=[this._events[a],f]:this._events[a]=f;e(this._events[a])&&!this._events[a].warned&&(k=void 0!==this._maxListeners?this._maxListeners:b.defaultMaxListeners)&&0<k&&this._events[a].length>k&&(this._events[a].warned=!0,console.error("(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.",this._events[a].length),"function"===
typeof console.trace&&console.trace());return this};b.prototype.on=b.prototype.addListener;b.prototype.once=function(a,b){function e(){this.removeListener(a,e);l||(l=!0,b.apply(this,arguments))}if(!c(b))throw TypeError("listener must be a function");var l=!1;e.listener=b;this.on(a,e);return this};b.prototype.removeListener=function(a,b){var k,l,d;if(!c(b))throw TypeError("listener must be a function");if(!this._events||!this._events[a])return this;k=this._events[a];d=k.length;l=-1;if(k===b||c(k.listener)&&
k.listener===b)delete this._events[a],this._events.removeListener&&this.emit("removeListener",a,b);else if(e(k)){for(;0<d--;)if(k[d]===b||k[d].listener&&k[d].listener===b){l=d;break}if(0>l)return this;1===k.length?(k.length=0,delete this._events[a]):k.splice(l,1);this._events.removeListener&&this.emit("removeListener",a,b)}return this};b.prototype.removeAllListeners=function(a){var b;if(!this._events)return this;if(!this._events.removeListener)return 0===arguments.length?this._events={}:this._events[a]&&
delete this._events[a],this;if(0===arguments.length){for(b in this._events)"removeListener"!==b&&this.removeAllListeners(b);this.removeAllListeners("removeListener");this._events={};return this}b=this._events[a];if(c(b))this.removeListener(a,b);else for(;b.length;)this.removeListener(a,b[b.length-1]);delete this._events[a];return this};b.prototype.listeners=function(a){return this._events&&this._events[a]?c(this._events[a])?[this._events[a]]:this._events[a].slice():[]};b.listenerCount=function(a,
b){return a._events&&a._events[b]?c(a._events[b])?1:a._events[b].length:0}},{}],2:[function(a,d,g){function b(a,f){if(!(this instanceof b))return new b(a,f);var c=this;f=f||{};a||(a=z.createElement("div"));c.element=a;e(c,f);w.set(c.element,c);c.id=t();c.ns="slidy-"+c.id;c.element.id||(c.element.id=c.ns);c.element.classList.add("slidy");c.pickers=[];h(f.pickers)&&f.pickers.length?f.pickers.forEach(function(a){a instanceof Node&&(a={element:a});var b=c.createPicker(a);c.pickers.push(b);void 0!==a.value&&
(b.value=a.value)}):(c.pickers.push(c.createPicker()),void 0!==f.value&&(c.value=f.value));Object.defineProperty(c,"value",{set:function(a){this.pickers[0].value=a},get:function(){return this.pickers[0].value}});c.aria&&(c.element.setAttribute("role","slider"),a.setAttribute("aria-valuemax",c.max),a.setAttribute("aria-valuemin",c.min),a.setAttribute("aria-orientation",c.type),a.setAttribute("aria-atomic",!0),a.setAttribute("aria-controls",c.pickers.map(function(a){return a.element.id}).join(" ")));
c.element.hasAttribute("disabled")||c.enable();c.emit("created")}var c=a("./lib/picker"),e=a("xtend/mutable"),h=a("is-array"),f=a("lifecycle-events");g=a("events");var k=a("emmy/on"),l=a("emmy/off"),n=a("emmy/throttle"),m=a("get-client-xy").x,p=a("get-client-xy").y,t=a("get-uid"),u=window,z=document;d.exports=b;var w=b.cache=new WeakMap;a=b.prototype=Object.create(g.prototype);a.min=0;a.max=100;a.value=50;a.type="horizontal";a.repeat=!1;a.keyboard=!0;a.aria=!0;a.wheel=!0;a.click=!0;a.point=!1;a.align=
.5;a.enable=function(){var a=this;if(a.isEnabled)return a;a.isEnabled=!0;a.aria&&a.element.removeAttribute("aria-disabled");a.element.removeAttribute("disabled");n(u,"resize."+a.ns,20,function(){a.update()});k(a.element,"attached."+a.ns,function(b){a.update()});f.enable(a.element);a.click&&k(a.element,"touchstart."+a.ns+" mousedown."+a.ns,function(b){b.preventDefault();a.element.focus();var c=a.element.getBoundingClientRect(),f=[],h,q,e;if(b.touches)for(var k=0,d=b.touches.length;k<d;k++)q=m(b,k)-
c.left,e=p(b,k)-c.top,h=a.getClosestPicker(a.pickers.filter(function(a){return 0>f.indexOf(a)}),q,e),f.push(h),h.move(q,e).startDrag(b);else q=m(b)-c.left,e=p(b)-c.top,h=a.getClosestPicker(a.pickers,q,e),f.push(h),h.move(q,e).startDrag(b),h.focus();a.pickers.forEach(function(a){0>f.indexOf(a)&&(a.draggable.state="idle")})});a.wheel&&k(a.element,"wheel."+a.ns+" mousewheel"+a.ns,function(b){var c=z.activeElement,f,h=a.element.getBoundingClientRect();if(c===a.element){f=m(b)-h.left;var q=p(b)-h.top;
f=a.getClosestPicker(a.pickers,f,q);f.focus()}else if(c.parentNode===a.element)f=a.pickers.filter(function(a){return a.element===c})[0];else return;b.preventDefault();var e=q=0;0!==b.deltaX&&(q=2*b.deltaX/h.width,q=0<q?Math.ceil(q):Math.floor(q),q=-q);0!==b.deltaY&&(e=2*b.deltaY/h.height,e=0<e?Math.ceil(e):Math.floor(e));f.inc(q,e)});a.keyboard&&a.element.setAttribute("tabindex",-1);a.pickers.forEach(function(a){a.enable()});return a};a.disable=function(){this.isEnabled=!1;this.aria&&this.element.setAttribute("aria-disabled",
!0);this.element.setAttribute("disabled",!0);l(u,"resize."+this.ns);l(this.element,"attached."+this.ns);l(this.element,"mousedown."+this.ns);l(this.element,"touchstart."+this.ns);this.pickers.forEach(function(a){a.disable()});return this};a.update=function(){this.pickers.forEach(function(a){a.update()})};a.createPicker=function(a){var b=this;a=e({within:b.element,type:b.type,min:b.min,max:b.max,repeat:b.repeat,step:b.step,snap:b.snap,pickerClass:b.pickerClass,align:b.align,release:b.release,aria:b.aria,
keyboard:b.keyboard,wheel:b.wheel,point:b.point,value:b.value},a);var f=a.element||document.createElement("div");b.aria&&f.setAttribute("aria-describedby",b.element.id);b.element.appendChild(f);a=new c(f,a);a.on("change",function(a){b.aria&&(b.element.setAttribute("aria-valuenow",a),b.element.setAttribute("aria-valuetext",a));b.emit("change",a)});return a};a.getClosestPicker=function(a,b,c){var f=9999,h;a.forEach(function(a){var e=a.draggable.getCoords(),k=b-e[0]-a.draggable.pin[0]-a.draggable.pin.width*
a.align,e=c-e[1]-a.draggable.pin[1]-a.draggable.pin.height*a.align,k=Math.sqrt(k*k+e*e);k<f&&(f=k,h=a)});return h}},{"./lib/picker":3,"emmy/off":20,"emmy/on":21,"emmy/throttle":22,events:1,"get-client-xy":23,"get-uid":24,"is-array":25,"lifecycle-events":27,"xtend/mutable":45}],3:[function(a,d,g){function b(a,c){if(!(this instanceof b))return new b(a,c);a||(a=B.createElement("div"));a.classList.add("slidy-picker");this.element=a;c.pickerClass&&a.classList.add(c.pickerClass);this.id=D();this.ns="slidy-picker-"+
this.id;this.element.id||(this.element.id=this.ns);this.draggable=new f(a,{threshold:0,within:c.within,sniperSlowdown:.85,axis:"x",repeat:this.repeat,releaseDuration:80});k(this,"type",this.type);y(this,c);this.enable();this.type=c.type;void 0===c.step&&(this.step=100>Math.abs(this.max-this.min)?.1:1);void 0===c.value&&(this.value=.5*(this.min+this.max))}function c(a,b,c){c=c||0;t(b)&&(b=b(a+(0<c?1E-5:-1E-5)));return a+b*c}function e(a,b,f,h,e){a[38]&&(b[1]=c(b[1],f,1));a[39]&&(b[0]=c(b[0],f,1));
a[40]&&(b[1]=c(b[1],f,-1));a[37]&&(b[0]=c(b[0],f,-1));var k=1;if(a[18]||a[91]||a[17]||a[16])k=0;a[36]&&(b[k]=h[k]);a[35]&&(b[k]=e[k]);a[33]&&(b[k]=c(b[k],f,5));a[34]&&(b[k]=c(b[k],f,-5));return b}function h(a,b,f,h,e){f=f||1;if(a[38]||a[39])b=c(b,f,1);if(a[40]||a[37])b=c(b,f,-1);a[36]&&(b=h);a[35]&&(b=e);a[33]&&(b=c(b,f,5));a[34]&&(b=c(b,f,-5));return b}var f=a("draggy"),k=a("define-state"),l=a("emmy/emit"),n=a("emmy/on"),m=a("emmy/off"),p=a("mucss/css");g=a("events");var t=a("is-function"),u=a("mumath/round"),
z=a("mumath/between"),w=a("mumath/loop"),D=a("get-uid"),r=a("is-array"),y=a("xtend/mutable");d.exports=b;var B=document,x=document.documentElement;a=b.prototype=Object.create(g.prototype);a.enable=function(){var a=this;if(a.isEnabled)return a;a.isEnabled=!0;a.aria&&a.element.removeAttribute("aria-disabled");a.element.removeAttribute("disabled");n(a.draggable,"dragstart."+a.ns,function(){p(x,"cursor","none");p(this.element,"cursor","none")});n(a.draggable,"drag",function(){if(!a.release||!a.draggable.isAnimated){var b=
a.calcValue.apply(a,a.draggable.getCoords());a.value=b;a.snap&&a.renderValue(a.value)}});n(a.draggable,"dragend."+a.ns,function(){a.release&&(a.draggable.isAnimated=!0);a.renderValue(a.value);p(x,"cursor",null);p(this.element,"cursor",null)});a.keyboard&&(a.element.setAttribute("tabindex",0),a._pressedKeys=[],n(a.element,"keydown."+a.ns,function(b){a._pressedKeys[b.which]=!0;33<=b.which&&40>=b.which&&(b.preventDefault(),a.value=a.handleKeys(a._pressedKeys,a.value,a.step,a.min,a.max),a.release&&(a.draggable.isAnimated=
!0),a.renderValue(a.value))}),n(a.element,"keyup."+a.ns,function(b){a._pressedKeys[b.which]=!1}));return a};a.disable=function(){this.isEnabled=!1;this.aria&&this.element.setAttribute("aria-disabled",!0);this.element.setAttribute("disabled",!0);m(this.element,"dragstart."+this.ns);m(this.element,"drag."+this.ns);m(this.element,"dragend."+this.ns);this.keyboard&&(this.element.setAttribute("tabindex",-1),m(this.element,"keydown."+this.ns),m(this.element,"keyup."+this.ns));return this};a.min=0;a.max=
100;a.step=1;a.snap=!1;a.release=!1;a.point=!1;a.align=.5;Object.defineProperties(a,{value:{set:function(a){if(void 0===a)throw Error("Picker value cannot be undefined.");this.repeat&&(r(a)&&"x"===this.repeat?a[0]=w(a[0],this.min[0],this.max[0]):r(a)&&"y"===this.repeat?a[1]=w(a[1],this.min[1],this.max[1]):a=w(a,this.min,this.max));a=z(a,this.min,this.max);this.step&&(a=t(this.step)?u(a,this.step(a)):u(a,this.step));this._value=a;this.emit("change",a);l(this.element,"change",a,!0)},get:function(){return this._value}}});
a.renderValue=function(a){};a.calcValue=function(a,b){};a.handleKeys=function(a,b,c){};a.update=function(){this.point&&(this.draggable.pin=[this.draggable.offsets.width*this.align,this.draggable.offsets.height*this.align]);this.draggable.update();this.renderValue(this.value);return this};a.move=function(a,b){if(this.point){var c=this.draggable.pin.height*this.align;a=a-this.draggable.pin[0]-this.draggable.pin.width*this.align;b=b-this.draggable.pin[1]-c}var c=this.draggable.pin.width-this.element.parentNode.clientWidth,
f=this.draggable.pin.height-this.element.parentNode.clientHeight;0<c&&(a-=c);0<f&&(b-=f);this.draggable.move(a,b);this.value=this.calcValue(a,b);return this};a.startDrag=function(a){this.draggable.setTouch(a).update(a);"drag"!==this.draggable.state&&(this.draggable.state="drag");this.draggable.innerOffsetX=this.draggable.pin[0]+.5*this.draggable.pin.width;this.draggable.innerOffsetY=this.draggable.pin[1]+.5*this.draggable.pin.height;this.draggable.drag(a);return this};a.focus=function(){this.element.focus()};
a.blur=function(){this.element.blur()};a.type={_:"horizontal",horizontal:function(){var a=this;a.draggable.axis="x";a.renderValue=function(b){var c=a.draggable.limits;a.move((b-a.min)/(a.max-a.min)*(c.right-c.left));return a};a.calcValue=function(b){var c=a.draggable.limits;return(b-c.left)/(c.right-c.left)*(a.max-a.min)+a.min};a.handleKeys=h},vertical:function(){var a=this;a.draggable.axis="y";a.renderValue=function(b){var c=a.draggable.limits;a.move(null,(-b+a.max)/(a.max-a.min)*(c.bottom-c.top));
return a};a.calcValue=function(b,c){var f=a.draggable.limits;return(-c+f.bottom)/(f.bottom-f.top)*(a.max-a.min)+a.min};a.handleKeys=h},rectangular:function(){var a=this;a.draggable.axis=null;a.renderValue=function(b){var c=a.draggable.limits;a.move((b[0]-a.min[0])/(a.max[0]-a.min[0])*(c.right-c.left),(-b[1]+a.max[1])/(a.max[1]-a.min[1])*(c.bottom-c.top));return a};a.calcValue=function(b,c){var f=a.draggable.limits,f=[(b-f.left)/(f.right-f.left),(-c+f.bottom)/(f.bottom-f.top)];return[f[0]*(a.max[0]-
a.min[0])+a.min[0],f[1]*(a.max[1]-a.min[1])+a.min[1]]};a.handleKeys=e},circular:function(){var a=this;a.draggable.axis=null;a.draggable.move=function(a,b){var c=this.limits,f=(c.right-c.left)/2-this.pin[0],c=(c.bottom-c.top)/2-this.pin[1],h=Math.atan2(b-c,a-f);this.setCoords(Math.cos(h)*(f+this.pin[0])+f,Math.sin(h)*(c+this.pin[1])+c)};a.renderValue=function(b){var c=a.draggable.limits,f=.5*(c.right-c.left),c=.5*(c.bottom-c.top);b=2*((b-a.min)/(a.max-a.min)-.5)*Math.PI;a.move(Math.cos(b)*f+f,Math.sin(b)*
c+c)};a.calcValue=function(b,c){var f=a.draggable.limits,h=f.bottom-f.top;b=b-.5*(f.right-f.left)+a.draggable.pin[0];c=c-.5*h+a.draggable.pin[1];return(.5*Math.atan2(c,b)/Math.PI+.5)*(a.max-a.min)+a.min};a.handleKeys=h},round:function(){var a=this;a.draggable.axis=null;a.draggable.move=function(a,b){var c=this.limits,f=c.right-c.left,c=c.bottom-c.top,h=f/2-this.pin[0],e=c/2-this.pin[1],A=a-h,k=b-e,d=Math.atan2(b-e,a-h),A=Math.sqrt(A*A+k*k);this.setCoords(A>f/2?Math.cos(d)*(h+this.pin[0])+h:a,A>c/
2?Math.sin(d)*(e+this.pin[1])+e:b)};a.renderValue=function(b){var c=a.draggable.limits,f=.5*(c.right-c.left),c=.5*(c.bottom-c.top),h=2*((b[0]-a.min[0])/(a.max[0]-a.min[0])-.5)*Math.PI,e=(b[1]-a.min[1])/(a.max[1]-a.min[1]);b=f*e;e*=c;a.move(Math.cos(h)*b+f,Math.sin(h)*e+c)};a.calcValue=function(b,c){var f=a.draggable.limits,h=f.right-f.left,f=f.bottom-f.top;b=b+a.draggable.pin[0]-.5*h;c=c+a.draggable.pin[1]-.5*f;f=.5*Math.atan2(c,b)/Math.PI+.5;h=Math.sqrt(b*b+c*c)/h*2;return[f*(a.max[0]-a.min[0])+
a.min[0],h*(a.max[1]-a.min[1])+a.min[1]]};a.handleKeys=e}};a.inc=function(a,b){r(this.value)?(this.value[0]=c(this.value[0],this.step,a),this.value[1]=c(this.value[1],this.step,b)):this.value=c(this.value,this.step,b||a);this.renderValue(this.value)}},{"define-state":4,draggy:9,"emmy/emit":11,"emmy/off":20,"emmy/on":21,events:1,"get-uid":24,"is-array":25,"is-function":26,"mucss/css":29,"mumath/between":39,"mumath/loop":40,"mumath/round":42,"xtend/mutable":45}],4:[function(a,d,g){d.exports=function(a,
e,h,f){f?a[e]=function(){return arguments.length?k.set(arguments[0]):k.get()}:Object.defineProperty(a,e,{set:function(a){return k.set(a)},get:function(){return k.get()}});var k=new b(h,a);return a};var b=a("st8")},{st8:5}],5:[function(a,d,g){function b(a,c){if(a instanceof b)return a;if(!(this instanceof b))return new b(a);this.states=a||{};this.context=c||this;this.isInit=!1}function c(a,b,c){return e(a[b])?a[b].call(c):a[b]}g=a("events");var e=a("is-function"),h=a("is-plain-object");b.options={leaveCallback:"after",
enterCallback:"before",changeCallback:"change",remainderState:"_"};a=b.prototype=Object.create(g.prototype);a.set=function(a){var e=this.state,d=this.states,g=void 0!==d[e]?e:b.options.remainderState,m=d[g],g=b.options.leaveCallback+g;if(this.isInit){if(h(m)&&!this[g]){this[g]=!0;m=c(m,b.options.leaveCallback,this.context);if(!1===m)return this[g]=!1;if(void 0!==m&&m!==a)return this.set(m),this[g]=!1;this[g]=!1;if(this.state!==e)return}if(a===e)return!1}else this.isInit=!0;this.state=a;var g=void 0!==
d[a]?a:b.options.remainderState,p=d[g],m=b.options.enterCallback+g;if(!this[m]){this[m]=!0;d=h(p)?c(p,b.options.enterCallback,this.context):c(d,g,this.context);if(!1===d)return this.set(e),this[m]=!1;if(void 0!==d&&d!==a)return this.set(d),this[m]=!1;this[m]=!1}a!==e&&this.emit(b.options.changeCallback,a,e);return this.context};a.get=function(){return this.state};d.exports=b},{events:1,"is-function":6,"is-plain-object":7}],6:[function(a,d,g){d.exports=function(a){var e=b.call(a);return"[object Function]"===
e||"function"===typeof a&&"[object RegExp]"!==e||"undefined"!==typeof window&&(a===window.setTimeout||a===window.alert||a===window.confirm||a===window.prompt)};var b=Object.prototype.toString},{}],7:[function(a,d,g){function b(a){return!0===c(a)&&"[object Object]"===Object.prototype.toString.call(a)}var c=a("isobject");d.exports=function(a){if(!1===b(a))return!1;a=a.constructor;if("function"!==typeof a)return!1;a=a.prototype;return!1===b(a)||!1===a.hasOwnProperty("isPrototypeOf")?!1:!0}},{isobject:8}],
8:[function(a,d,g){d.exports=function(a){return null!=a&&"object"===typeof a&&!Array.isArray(a)}},{}],9:[function(a,d,g){function b(a,c){if(!(this instanceof b))return new b(a,c);this._id=H();this._ns=".draggy_"+this._id;this.element=a;I.set(a,this);r(this,"css3",this.css3);this.css3=!0;r(this,"state",this.state);this.state="idle";r(this,"axis",this.axis);this.axis=null;r(this,"isAnimated",this.isAnimated);y(this,c);this.update()}function c(a){if(!(a[0]||a[1]||a[2]||a[3]))return!0}var e=a("mucss/css"),
h=a("mucss/parse-value"),f=a("mucss/selection"),k=a("mucss/offsets"),l=a("mucss/translate"),n=a("emmy/on"),m=a("emmy/off"),p=a("emmy/emit");g=a("events");var t=a("get-client-xy").x,u=a("get-client-xy").y,z=a("is-array"),w=a("is-number"),D=a("is-function"),r=a("define-state"),y=a("xtend/mutable"),B=a("mumath/round"),x=a("mumath/between"),q=a("mumath/loop"),H=a("get-uid"),F=window,v=document,G=v.documentElement,I=b.cache=new WeakMap;a=b.prototype=Object.create(g.prototype);a.state={_:{before:function(){var a=
this;p(a.element,"idle",null,!0);a.emit("idle");n(a.element,"mousedown"+a._ns+" touchstart"+a._ns,function(b){b.preventDefault();a.setTouch(b);a.update(b);a.state="threshold"})},after:function(){var a=this;m(a.element,"touchstart"+a._ns+" mousedown"+a._ns);a.release&&(a._trackingInterval=setInterval(function(b){var c=Date.now()-a.timestamp;b=a.prevX-a.frame[0];var f=a.prevY-a.frame[1];a.frame[0]=a.prevX;a.frame[1]=a.prevY;var h=Math.sqrt(b*b+f*f),c=Math.min(a.velocity*h/(1+c),a.maxSpeed);a.speed=
.8*c+.2*a.speed;a.angle=Math.atan2(f,b);a.emit("track");return a},a.framerate))}},threshold:{before:function(){var a=this;c(a.threshold)?a.state="drag":(a.emit("threshold"),n(v,"touchmove"+a._ns+" mousemove"+a._ns,function(b){b.preventDefault();var c=t(b,a.touchIdx),f=u(b,a.touchIdx),c=a.prevMouseX-c,f=a.prevMouseY-f;if(c<a.threshold[0]||c>a.threshold[2]||f<a.threshold[1]||f>a.threshold[3])a.update(b),a.state="drag"}),n(v,"mouseup"+a._ns+" touchend"+a._ns+"",function(b){b.preventDefault();a.resetTouch();
a.state="idle"}))},after:function(){m(v,"touchmove"+this._ns+" mousemove"+this._ns+" mouseup"+this._ns+" touchend"+this._ns)}},drag:{before:function(){var a=this;f.disable(G);a.emit("dragstart");p(a.element,"dragstart",null,!0);a.emit("drag");p(a.element,"drag",null,!0);n(v,"touchend"+a._ns+" mouseup"+a._ns+" mouseleave"+a._ns,function(b){b.preventDefault();a.resetTouch();a.state=1<a.speed?"release":"idle"});n(v,"touchmove"+a._ns+" mousemove"+a._ns,function(b){a.drag(b)})},after:function(){f.enable(G);
this.emit("dragend");p(this.element,"dragend",null,!0);m(v,"touchend"+this._ns+" mouseup"+this._ns+" mouseleave"+this._ns);m(v,"touchmove"+this._ns+" mousemove"+this._ns);clearInterval(this._trackingInterval)}},release:{before:function(){this.isAnimated=!0;this.move(this.prevX+this.speed*Math.cos(this.angle),this.prevY+this.speed*Math.sin(this.angle));this.speed=0;this.emit("track");this.state="idle"}}};a.drag=function(a){a.preventDefault();var b=t(a,this.touchIdx),c=u(a,this.touchIdx),f=b-this.prevMouseX,
h=c-this.prevMouseY,e=b+F.pageXOffset,k=c+F.pageYOffset;if(a.ctrlKey||a.metaKey)this.sniperOffsetX+=f*this.sniperSlowdown,this.sniperOffsetY+=h*this.sniperSlowdown;this.move(e-this.initOffsetX-this.innerOffsetX-this.sniperOffsetX,k-this.initOffsetY-this.innerOffsetY-this.sniperOffsetY);this.prevMouseX=b;this.prevMouseY=c;this.emit("drag");p(this.element,"drag",null,!0)};var E=0;a.setTouch=function(a){if(!a.touches||this.isTouched())return this;this.touchIdx=E;E++;return this};a.resetTouch=function(){E=
0;this.touchIdx=null;return this};a.isTouched=function(){return null!==this.touchIdx};a.isAnimated={"true":{before:function(){var a=this;clearTimeout(a._animateTimeout);e(a.element,{transition:a.releaseDuration+"ms ease-out "+(a.css3?"transform":"position")});a._animateTimeout=setTimeout(function(){a.isAnimated=!1},a.releaseDuration)},after:function(){e(this.element,{transition:null})}}};a.touchIdx=null;a.update=function(a){var b=this.getCoords();this.prevX=b[0];this.prevY=b[1];b=k(this.element);
this.initOffsetX=b.left-this.prevX;this.initOffsetY=b.top-this.prevY;this.offsets=b;"parent"===this.within&&(this.within=this.element.parentNode||v);this.withinOffsets=b=k(this.within);this.overflowX=this.pin.width-b.width;this.overflowY=this.pin.height-b.height;this.limits={left:b.left-this.initOffsetX-this.pin[0]-(0>this.overflowX?0:this.overflowX),top:b.top-this.initOffsetY-this.pin[1]-(0>this.overflowY?0:this.overflowY),right:0<this.overflowX?0:b.right-this.initOffsetX-this.pin[2],bottom:0<this.overflowY?
0:b.bottom-this.initOffsetY-this.pin[3]};this.innerOffsetX=this.pin[0];this.innerOffsetY=this.pin[1];b=this.element.getBoundingClientRect();if(a)this.prevMouseX=t(a,this.touchIdx),this.prevMouseY=u(a,this.touchIdx),this.innerOffsetX=-b.left+t(a,this.touchIdx),this.innerOffsetY=-b.top+u(a,this.touchIdx);else{a=.5*(this.pin[0]+this.pin[2]);var c=.5*(this.pin[1]+this.pin[3]);this.prevMouseX=b.left+a;this.prevMouseY=b.top+c;this.innerOffsetX=a;this.innerOffsetY=c}this.angle=this.amplitude=this.speed=
0;this.timestamp=+new Date;this.frame=[this.prevX,this.prevY];this.sniperOffsetY=this.sniperOffsetX=0};a.css3={_:function(){this.getCoords=function(){return[h(e(this.element,"left")),h(e(this.element,"top"))]};this.setCoords=function(a,b){e(this.element,{left:a,top:b});this.prevX=a;this.prevY=b}},"true":function(){this.getCoords=function(){return l(this.element)||[0,0]};this.setCoords=function(a,b){a=B(a,this.precition);b=B(b,this.precition);e(this.element,"transform",["translate3d(",a,"px,",b,"px, 0)"].join(""));
this.prevX=a;this.prevY=b}}};a.within=v;Object.defineProperties(a,{pin:{set:function(a){z(a)?2===a.length?this._pin=[a[0],a[1],a[0],a[1]]:4===a.length&&(this._pin=a):w(a)?this._pin=[a,a,a,a]:this._pin=a;this._pin.width=this._pin[2]-this._pin[0];this._pin.height=this._pin[3]-this._pin[1]},get:function(){if(this._pin)return this._pin;var a=[0,0,this.offsets.width,this.offsets.height];a.width=this.offsets.width;a.height=this.offsets.height;return a}},threshold:{set:function(a){w(a)?this._threshold=[.5*
-a,.5*-a,.5*a,.5*a]:2===a.length?this._threshold=[.5*-a[0],.5*-a[1],.5*a[0],.5*a[1]]:4===a.length?this._threshold=a:D(a)?this._threshold=a():this._threshold=[0,0,0,0]},get:function(){return this._threshold||[0,0,0,0]}}});a.release=!1;a.releaseDuration=500;a.velocity=1E3;a.maxSpeed=250;a.framerate=50;a.precision=1;a.sniper=!0;a.sniperSlowdown=.85;a.axis={_:function(){this.move=function(a,b){var c=this.limits;if(this.repeat){var f=c.right-c.left,h=c.bottom-c.top,e=-this.initOffsetX+this.withinOffsets.left-
this.pin[0]-Math.max(0,this.overflowX),k=-this.initOffsetY+this.withinOffsets.top-this.pin[1]-Math.max(0,this.overflowY);"x"===this.repeat?a=q(a-e,f)+e:("y"!==this.repeat&&(a=q(a-e,f)+e),b=q(b-k,h)+k)}a=x(a,c.left,c.right);b=x(b,c.top,c.bottom);this.setCoords(a,b)}},x:function(){this.move=function(a,b){var c=this.limits;if(this.repeat){var c=c.right-c.left,f=-this.initOffsetX+this.withinOffsets.left-this.pin[0]-Math.max(0,this.overflowX);a=q(a-f,c)+f}else a=x(a,c.left,c.right);this.setCoords(a,this.prevY)}},
y:function(){this.move=function(a,b){var c=this.limits;if(this.repeat){var c=c.bottom-c.top,f=-this.initOffsetY+this.withinOffsets.top-this.pin[1]-Math.max(0,this.overflowY);b=q(b-f,c)+f}else b=x(b,c.top,c.bottom);this.setCoords(this.prevX,b)}}};a.repeat=!1;d.exports=b},{"define-state":4,"emmy/emit":11,"emmy/off":20,"emmy/on":21,events:1,"get-client-xy":23,"get-uid":24,"is-array":25,"is-function":26,"is-number":10,"mucss/css":29,"mucss/offsets":33,"mucss/parse-value":34,"mucss/selection":37,"mucss/translate":38,
"mumath/between":39,"mumath/loop":40,"mumath/round":42,"xtend/mutable":45}],10:[function(a,d,g){d.exports=function(a){return!!+a&&!Array.isArray(a)&&isFinite(a)||"0"===a||0===a}},{}],11:[function(a,d,g){function b(a,b,h,d){var g,r=b;f(a)||a===p?(k(b)?r=b:(r=m.createEvent("CustomEvent"),r.initCustomEvent(b,d,!0,h)),g=a.dispatchEvent):n&&a instanceof n?(r=n.Event(b,h),r.detail=h,g=d?targte.trigger:a.triggerHandler):g=a.emit||a.trigger||a.fire||a.dispatchEvent||a.raise;var y=e(arguments,2);if(g&&c.freeze(a,
"emit"+b))return g.apply(a,[r].concat(y)),c.unfreeze(a,"emit"+b),a;g=l(a,r);g=e(g);for(r=0;r<g.length;r++)g[r]&&g[r].apply(a,y);return a}var c=a("icicle"),e=a("sliced"),h=a("mutype/is-string"),f=a("mutype/is-node"),k=a("mutype/is-event"),l=a("./listeners");d.exports=function(a,c){if(a){var f=arguments;if(h(c))f=e(arguments,2),c.split(/\s+/).forEach(function(c){c=c.split(".")[0];b.apply(this,[a,c].concat(f))});else return b.apply(this,f)}};var n="undefined"===typeof jQuery?void 0:jQuery,m="undefined"===
typeof document?void 0:document,p="undefined"===typeof window?void 0:window},{"./listeners":12,icicle:13,"mutype/is-event":14,"mutype/is-node":16,"mutype/is-string":17,sliced:18}],12:[function(a,d,g){function b(a,b,k){a=e.get(a);if(!b)return a||{};if(!a||!a[b])return[];b=a[b];k&&k.length&&(b=b.filter(function(a){return c(a,k)}));return b}function c(a,b){if(a._ns)for(var c=b.length;c--;)if(0<=a._ns.indexOf(b[c]))return!0}var e=new WeakMap;b.remove=function(a,b,k,d){a=e.get(a);if(!a||!a[b])return!1;
b=a[b];if(d&&d.length&&!c(k,d))return!1;for(d=0;d<b.length;d++)if(b[d]===k||b[d].fn===k){b.splice(d,1);break}};b.add=function(a,b,c,d){c&&(e.has(a)||e.set(a,{}),a=e.get(a),(a[b]=a[b]||[]).push(c),d&&d.length&&(c._ns=d))};d.exports=b},{}],13:[function(a,d,g){d.exports={freeze:function(a,e){var h=b.get(a);if(h&&h[e])return!1;h||(h={},b.set(a,h));return h[e]=!0},unfreeze:function(a,e){var h=b.get(a);if(!h||!h[e])return!1;h[e]=null;return!0},isFrozen:function(a,e){var h=b.get(a);return h&&h[e]}};var b=
new WeakMap},{}],14:[function(a,d,g){d.exports=function(a){return"undefined"!==typeof Event&&a instanceof Event}},{}],15:[function(a,d,g){d.exports=function(a){return!(!a||!a.apply)}},{}],16:[function(a,d,g){d.exports=function(a){return"undefined"!==typeof document&&a instanceof Node}},{}],17:[function(a,d,g){d.exports=function(a){return"string"===typeof a||a instanceof String}},{}],18:[function(a,d,g){d.exports=a("./lib/sliced")},{"./lib/sliced":19}],19:[function(a,d,g){d.exports=function(a,c,e){var h=
[],f=a.length;if(0===f)return h;c=0>c?Math.max(0,c+f):c||0;for(void 0!==e&&(f=0>e?e+f:e);f-- >c;)h[f-c]=a[f];return h}},{}],20:[function(a,d,g){function b(a,d,g){if(!a)return a;var n;if(void 0===g){var m=e(arguments,1),p=a.removeAll||a.removeAllListeners;p&&p.apply(a,m);if(d)d.split(/\s+/).forEach(function(c){var e=c.split(".");c=e.shift();n=h(a,c,e);for(e=n.length;e--;)b(a,c,n[e])});else for(d in n=h(a),n)b(a,d);return a}var t=a.off||a.removeEventListener||a.removeListener||a.detachEvent;d.split(/\s+/).forEach(function(b){var e=
b.split(".");b=e.shift();if(t)if(c.freeze(a,"off"+b))t.call(a,b,g),c.unfreeze(a,"off"+b);else return a;g.closedCall&&(g.closedCall=!1);h.remove(a,b,g,e)});return a}d.exports=b;var c=a("icicle"),e=a("sliced"),h=a("./listeners")},{"./listeners":12,icicle:13,sliced:18}],21:[function(a,d,g){function b(a,b,d){if(!a)return a;var g=a.on||a.addEventListener||a.addListener||a.attachEvent;b.split(/\s+/).forEach(function(b){var f=b.split(".");b=f.shift();if(g)if(c.freeze(a,"on"+b))g.call(a,b,d),c.unfreeze(a,
"on"+b);else return a;e.add(a,b,d,f)});return a}var c=a("icicle"),e=a("./listeners");d.exports=b;b.wrap=function(a,b,c,e){b=function(){if(e.apply(a,arguments))return c.apply(a,arguments)};b.fn=c;return b}},{"./listeners":12,icicle:13}],22:[function(a,d,g){function b(a,f,e,d){return c(a,f,b.wrap(a,f,e,d))}d.exports=b;var c=a("./on");a("./off");var e=a("mutype/is-fn");b.wrap=function(a,b,c,d){e(d)&&(b=d,d=c,c=b);var g=function(){g.closedInterval?g.closedCall=!0:(g.closedCall=!1,c.apply(a,arguments),
g.closedInterval=setTimeout(function(){g.closedInterval=null;g.closedCall&&g.apply(a,arguments)},d))};g.fn=c;return g}},{"./off":20,"./on":21,"mutype/is-fn":15}],23:[function(a,d,g){function b(a,b){return a.touches?b||0===b?a.touches[b].clientY:a.targetTouches[0].clientY:a.clientY}function c(a,b){return a.touches?b||0===b?a.touches[b].clientX:a.targetTouches[0].clientX:a.clientX}function e(a,e){return[c(a,e),b(a,e)]}e.x=c;e.y=b;d.exports=e},{}],24:[function(a,d,g){var b=Date.now()%1E9;d.exports=function(){return(1E9*
Math.random()>>>0)+b++}},{}],25:[function(a,d,g){var b=Object.prototype.toString;d.exports=Array.isArray||function(a){return!!a&&"[object Array]"==b.call(a)}},{}],26:[function(a,d,g){arguments[4][6][0].apply(g,arguments)},{dup:6}],27:[function(a,d,g){function b(a,b){a||(a="*");b=h(b||f);n.push(a);l.observe(b,{subtree:!0,childList:!0});a instanceof Node&&!f.contains(a)||c(h.call(b,a,!0))}function c(a){for(var b=!1,c,f=a.length;f--;)if(c=a[f],1===c.nodeType&&!m.has(c)){a:{for(var d=n.length,h=void 0;d--;){h=
n[d];if(c===h)break a;if("string"===typeof h&&c.matches(h))break a;if(c.contains(h)){c=h;break a}}c=void 0}c&&(b||(b=!0),m.add(c),e(c,k.attachedCallbackName,null,!0))}}a("emmy/on");var e=a("emmy/emit");a("emmy/off");var h=a("tiny-element"),f=document,k=d.exports=b;k.enable=b;k.disable=function(a){a=n.indexOf(a);0<=a&&n.splice(a,1)};k.attachedCallbackName="attached";k.detachedCallbackName="detached";var l=new (window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver)(function(a){a.forEach(function(a){c(a.addedNodes);
a=a.removedNodes;for(var b=a.length;b--;){var f=a[b];1===f.nodeType&&m.has(f)&&(e(f,k.detachedCallbackName,null,!0),m["delete"](f))}})}),n=[],m=new WeakSet},{"emmy/emit":11,"emmy/off":20,"emmy/on":21,"tiny-element":44}],28:[function(a,d,g){d.exports=function(a,c,e,d,f,k){this.top=c||0;this.bottom=d||0;this.left=a||0;this.right=e||0;void 0!==f&&(this.width=f||this.right-this.left);void 0!==k&&(this.height=k||this.bottom-this.top)}},{}],29:[function(a,d,g){function b(a){var b=a[0].toUpperCase()+a.slice(1);
return void 0!==c[a]?a:void 0!==c[e+b]?e+b:""}var c=a("./fake-element").style,e=a("./prefix").dom;d.exports=function(a,c){if(a&&c){var e,d;if("string"===typeof c){e=c;if(3>arguments.length)return a.style[b(e)];d=arguments[2]||"";c={};c[e]=d}for(e in c)"number"===typeof c[e]&&/left|right|bottom|top|width|height/i.test(e)&&(c[e]+="px"),d=c[e]||"",a.style[b(e)]=d}}},{"./fake-element":30,"./prefix":35}],30:[function(a,d,g){d.exports=document.createElement("div")},{}],31:[function(a,d,g){g.x=function(){return win.innerHeight>
root.clientHeight};g.y=function(){return win.innerWidth>root.clientWidth}},{}],32:[function(a,d,g){d.exports=function(a){var c=a;if(a===window)return!0;if(a===document)return!1;for(;c;){if("fixed"===getComputedStyle(c).position)return!0;c=c.offsetParent}return!1}},{}],33:[function(a,d,g){var b=window,c=a("./Rect"),e=a("./has-scroll"),h=a("./scrollbar"),f=a("./is-fixed");d.exports=function(a){if(!a)throw Error("Bad argument");var d;if(a===b)return a=new c(b.pageXOffset,b.pageYOffset),a.width=b.innerWidth-
(e.y()?h:0),a.height=b.innerHeight-(e.x()?h:0),a.right=a.left+a.width,a.bottom=a.top+a.height,a;try{d=a.getBoundingClientRect()}catch(g){d=new c(a.clientLeft,a.clientTop)}var m=f(a),p=m?0:b.pageXOffset,m=m?0:b.pageYOffset;return a=new c(d.left+p,d.top+m,d.left+p+a.offsetWidth,d.top+m+a.offsetHeight,a.offsetWidth,a.offsetHeight)}},{"./Rect":28,"./has-scroll":31,"./is-fixed":32,"./scrollbar":36}],34:[function(a,d,g){d.exports=function(a){return parseFloat((a+"").slice(0,-2))||0}},{}],35:[function(a,
d,g){a=getComputedStyle(document.documentElement,"");a=(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||""===a.OLink&&["","o"])[1];dom="WebKit|Moz|MS|O".match(new RegExp("("+a+")","i"))[1];d.exports={dom:dom,lowercase:a,css:"-"+a+"-",js:a[0].toUpperCase()+a.substr(1)}},{}],36:[function(a,d,g){a=document.createElement("div");g=a.style;g.width="100px";g.height="100px";g.overflow="scroll";g.position="absolute";g.top="-9999px";document.body.appendChild(a);d.exports=a.offsetWidth-a.clientWidth;
document.body.removeChild(a)},{}],37:[function(a,d,g){function b(a){a.preventDefault()}var c=a("./css");g.disable=function(a){c(a,{"user-select":"none","user-drag":"none","touch-callout":"none"});a.setAttribute("unselectable","on");a.addEventListener("selectstart",b)};g.enable=function(a){c(a,{"user-select":null,"user-drag":null,"touch-callout":null});a.removeAttribute("unselectable");a.removeEventListener("selectstart",b)}},{"./css":29}],38:[function(a,d,g){var b=a("./css"),c=a("./parse-value");
d.exports=function(a){a=b(a,"transform");return(a=/translate(?:3d)?\s*\(([^\)]*)\)/.exec(a))?a[1].split(/\s*,\s*/).map(function(a){return c(a)}):null}},{"./css":29,"./parse-value":34}],39:[function(a,d,g){d.exports=a("./wrap")(function(a,c,e){return e>c?Math.max(Math.min(a,e),c):Math.max(Math.min(a,c),e)})},{"./wrap":43}],40:[function(a,d,g){d.exports=a("./wrap")(function(a,c,e){void 0===e&&(e=c,c=0);if(c>e){var d=e;e=c;c=d}d=e-c;a=(a+c)%d-c;a<c&&(a+=d);a>e&&(a-=d);return a})},{"./wrap":43}],41:[function(a,
d,g){d.exports=a("./wrap")(function(a){a+="";var c=a.indexOf(".")+1;return c?a.length-c:0})},{"./wrap":43}],42:[function(a,d,g){var b=a("./precision");d.exports=a("./wrap")(function(a,e){if(0===e)return a;if(!e)return Math.round(a);e=parseFloat(e);a=Math.round(a/e)*e;return parseFloat(a.toFixed(b(e)))})},{"./precision":41,"./wrap":43}],43:[function(a,d,g){d.exports=function(a){return function(c){var e=arguments;if(c instanceof Array){for(var d=Array(c.length),f,g=0;g<c.length;g++){f=[];for(var l=
0,n=e.length,m;l<n;l++)m=e[l]instanceof Array?e[l][g]:e[l],f.push(m);d[g]=a.apply(this,f)}return d}if("object"===typeof c){d={};for(g in c){f=[];l=0;for(n=e.length;l<n;l++)m="object"===typeof e[l]?e[l][g]:e[l],f.push(m);d[g]=a.apply(this,f)}return d}return a.apply(this,e)}}},{}],44:[function(a,d,g){var b=[].slice;d.exports=function(a,d){var g=this===window?document:this;return"string"==typeof a?d?b.call(g.querySelectorAll(a),0):g.querySelector(a):a instanceof Node||a===window||!a.length?d?[a]:a:b.call(a,
0)}},{}],45:[function(a,d,g){d.exports=function(a){for(var c=1;c<arguments.length;c++){var d=arguments[c],g;for(g in d)d.hasOwnProperty(g)&&(a[g]=d[g])}return a}},{}]},{},[2])(2)});
